export const ModelRepository = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  CUSTOMER_REPOSITORY: 'CUSTOMER_REPOSITORY',
  COUNTRY_REPOSITORY: 'COUNTRY_REPOSITORY',
  ACQUISITION_CHANNEL_REPOSITORY: 'ACQUISITION_CHANNEL_REPOSITORY',
  SALE_REPOSITORY: 'SALE_REPOSITORY',
};
